// schueler/react-hexapawn/src/view/App.tsx
import { Box } from '@material-ui/core';
import React from 'react';
import { SpielProvider } from '../spiel-service/Spiel.context';

function App(): JSX.Element {
  return (
    <SpielProvider>
      <Box display='flex' alignItems='center' justifyContent='center' height='100vh'>
        Hier kommt später das Spielfeld hin.
      </Box>
    </SpielProvider>
  );
}

export default App;

// schueler/angular-hexapawn/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'Angular Hexapawn';
}

<div class="root">
  <span>Hier kommt später das Spielfeld hin.</span>
</div>
