// loesungen/angular-hexapawn/src/app/observable-zaehler/observable-zaehler.component.ts
import { Component } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Component({
  selector: 'app-observable-zaehler',
  templateUrl: './observable-zaehler.component.html',
  styleUrls: ['./observable-zaehler.component.scss'],
})
export class ObservableZaehlerComponent {
  readonly zaehler$ = new BehaviorSubject<number>(0);

  constructor() {}

  erhoeheZaehler() {
    this.zaehler$.next(this.zaehler$.value + 1);
  }

  verringereZaehler() {
    this.zaehler$.next(this.zaehler$.value - 1);
  }
}

<div class="box">
  <button (click)="erhoeheZaehler()" mat-stroked-button color="primary">Erhöhen</button>
  <span>Aktuell: {{ zaehler$ | async }}</span>
  <button (click)="verringereZaehler()" mat-stroked-button color="primary">Verringern</button>
</div>

// loesungen/react-hexapawn/src/ObservableZaehler.tsx
import React from 'react';
import { BehaviorSubject } from 'rxjs';
import useObservable from './helpers/useObservable';
import { Box, Button, Typography } from '@material-ui/core';

const zaehler$ = new BehaviorSubject<number>(0);

function ObservableZaehler(): JSX.Element {
  const aktuelleZahl = useObservable(zaehler$) ?? 0;

  return (
    <Box display='flex' flexDirection='column'>
      <Button variant='contained' onClick={() => zaehler$.next(aktuelleZahl + 1)}>
        Erhöhen
      </Button>

      <Typography>Aktuell: {aktuelleZahl}</Typography>

      <Button variant='contained' onClick={() => zaehler$.next(aktuelleZahl - 1)}>
        Verringern
      </Button>
    </Box>
  );
}

export default ObservableZaehler;
